"""empty message

Revision ID: 039d914d666b
Revises: d1b17a31cf53
Create Date: 2021-06-28 13:36:44.106418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039d914d666b'
down_revision = 'd1b17a31cf53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
